# Generated by Django 5.0.14 on 2026-07-06 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(help_text='Event classification title (e.g., USER_LOGIN).', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional event context parameters.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PAYOUT_APPROVAL', 'Payout Approval'), ('SYLLABUS_AUDIT', 'Syllabus Audit Check'), ('CERTIFICATE_SIGNING', 'Certificate Signing'), ('USER_SUSPENSION', 'Account Verification')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed')], default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Metadata or specific action parameters.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Administrative Task',
                'verbose_name_plural': 'Administrative Tasks',
                'db_table': 'control_administrative_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True)),
                ('title', models.CharField(default='New Conversation', help_text='Custom name of discussion thread.', max_length=255)),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'db_table': 'ai_conversations',
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_positive', models.BooleanField(help_text='True representing Thumbs Up, False representing Thumbs Down.')),
                ('feedback_text', models.TextField(blank=True, help_text='Additional qualitative textual review.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Feedback',
                'verbose_name_plural': 'AI Feedbacks',
                'db_table': 'ai_feedback',
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('USER', 'User Prompt'), ('ASSISTANT', 'Assistant Response')], help_text='Classifier tag indicating prompt vs model output.', max_length=20)),
                ('content', models.TextField(help_text='Raw or markdown text content.')),
                ('token_count', models.IntegerField(default=0, help_text='Token diagnostics tracking count.')),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'db_table': 'ai_messages',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(help_text='Telemetry identifier (e.g., video_playback_sec).', max_length=100)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=4, help_text='Numeric telemetry quantity.', max_digits=15, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Dynamic telemetry details payload.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Visual heading (e.g., Total Students)', max_length=100)),
                ('metric_type', models.CharField(choices=[('DB_COUNT', 'Database Count Query'), ('DB_SUM', 'Database Sum/Aggregate Query'), ('TELEMETRY_RATE', 'Telemetry Event Rate'), ('STATIC_VALUE', 'Fixed Parameter')], default='DB_COUNT', max_length=30)),
                ('query_target', models.CharField(help_text='Specifies target entity or SQL aggregate routine (e.g., lms.CourseStructure.count)', max_length=255)),
                ('color_scheme', models.CharField(default='indigo', help_text='Tailwind display scheme color class', max_length=50)),
                ('icon_name', models.CharField(default='Activity', help_text='Lucide icon identifier name', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('required_role', models.CharField(default='role-super-admin', max_length=100)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'db_table': 'control_dashboard_widgets',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Unique configuration setting key name.', max_length=255, unique=True)),
                ('value', models.JSONField(help_text='Arbitrary JSON settings document.')),
                ('description', models.TextField(blank=True, help_text="Short description outlining setting's purpose.", null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(help_text='Mutation action name (e.g., ROLE_MODIFIED).', max_length=100)),
                ('target_table', models.CharField(help_text='Physical database table modified.', max_length=100)),
                ('before_state', models.JSONField(blank=True, help_text='State snapshot prior to modification.', null=True)),
                ('after_state', models.JSONField(blank=True, help_text='State snapshot subsequent to modification.', null=True)),
                ('ip_address', models.CharField(blank=True, help_text='IP address of executing system client.', max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Audit Log',
                'verbose_name_plural': 'System Audit Logs',
                'db_table': 'system_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Aesthetic theme name (e.g., Calm Amber, Slate Twilight).', max_length=100, unique=True)),
                ('colors', models.JSONField(help_text="Custom palette mappings (e.g., {'primary': '#F59E0B'}).")),
                ('is_active', models.BooleanField(default=False, help_text='Is current custom theme active?')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
                'db_table': 'themes',
            },
        ),
    ]
