# Generated by Django 5.0.14 on 2026-07-06 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Active user session performer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(help_text='Owner user dialog participant.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(help_text='Parent discussion session thread.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='control_center.aiconversation'),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='message',
            field=models.OneToOneField(help_text='Target message feedback rating target.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='control_center.aimessage'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Active user logging metric.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User actor responsible for modification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audits', to=settings.AUTH_USER_MODEL),
        ),
    ]
