# Generated by Django 5.1.4 on 2026-07-08 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_center', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Original file name.', max_length=255)),
                ('file_url', models.CharField(help_text='Fully qualified URL or storage key.', max_length=512)),
                ('file_type', models.CharField(help_text='MIME type classification (e.g. image/png, video/mp4, application/pdf).', max_length=100)),
                ('file_size', models.BigIntegerField(help_text='Size of file in bytes.')),
                ('purpose', models.CharField(choices=[('AVATAR', 'User Profile Picture'), ('COVER', 'User Profile Cover'), ('COURSE_FILE', 'LMS Lesson File'), ('BOOK_FILE', 'Store E-Book File'), ('CERTIFICATE', 'Syllabus Certificate File')], default='COURSE_FILE', max_length=50)),
                ('version', models.IntegerField(default=1, help_text='File version increments.')),
                ('uploader', models.ForeignKey(blank=True, help_text='User who uploaded the file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'db_table': 'media_files',
            },
        ),
    ]
