# Generated by Django 5.1.4 on 2026-07-08 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0004_liveclass'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Publisher company name.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Details of publisher.', null=True)),
                ('website_url', models.CharField(blank=True, max_length=512, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=512, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Publisher Profile',
                'verbose_name_plural': 'Publisher Profiles',
                'db_table': 'publisher_profiles',
            },
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Author public display name.', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Biographical summary.', null=True)),
                ('avatar_url', models.CharField(blank=True, help_text='Avatar picture link.', max_length=512, null=True)),
                ('verified', models.BooleanField(default=False, help_text='Is this author verified by the platform?')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Custom attributes.')),
                ('user', models.ForeignKey(help_text='The system user account owning this author profile.', on_delete=django.db.models.deletion.RESTRICT, related_name='author_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Author Profile',
                'verbose_name_plural': 'Author Profiles',
                'db_table': 'author_profiles',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Book header title.', max_length=255)),
                ('slug', models.CharField(help_text='URL slug identifier.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, help_text='ISBN index value.', max_length=50, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('book_type', models.CharField(choices=[('EBOOK', 'E-Book'), ('PHYSICAL', 'Physical Book'), ('AUDIOBOOK', 'Audiobook')], default='EBOOK', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cover_image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('preview_file_url', models.CharField(blank=True, help_text='Sample booklet file link.', max_length=512, null=True)),
                ('full_file_url', models.CharField(blank=True, help_text='Complete content file link.', max_length=512, null=True)),
                ('inventory_count', models.IntegerField(default=0, help_text='Stock count for physical books.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadata including tags, categories, languages.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='publishing.authorprofile')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='publishing.publisherprofile')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publishing.book')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.coursestructure')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='publishing.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='ProductOwnership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('PLATFORM', 'Platform'), ('TEACHER', 'Teacher'), ('AUTHOR', 'Author'), ('ORGANIZATION', 'Organization')], default='PLATFORM', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.1, help_text='Percentage commission for platform (e.g. 0.10 for 10%).', max_digits=5)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='publishing.book')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='lms.coursestructure')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to=settings.AUTH_USER_MODEL)),
                ('wallet_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Product Ownership',
                'verbose_name_plural': 'Product Ownerships',
                'db_table': 'product_ownerships',
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='publishing.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Progress',
                'verbose_name_plural': 'Reading Progresses',
                'db_table': 'reading_progress',
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='uq_reading_progress_user_book')],
            },
        ),
    ]
