# Generated by Django 5.1.4 on 2026-07-10 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('opened_count', models.IntegerField(default=0)),
                ('clicked_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('avg_delivery_time_ms', models.FloatField(default=0.0)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'db_table': 'notification_analytics',
                'ordering': ['-date'],
            },
        ),
    ]
