# Generated by Django 5.1.4 on 2026-07-08 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('WEBSITE_DEVELOPMENT', 'Website Development'), ('APPLICATION_DEVELOPMENT', 'Application Development'), ('UI_UX_DESIGN', 'UI/UX Design'), ('SEO', 'SEO & Digital Marketing'), ('BUSINESS_CONSULTING', 'Business Consulting'), ('CAREER_CONSULTING', 'Career Consulting'), ('CUSTOM_ENTERPRISE', 'Custom Enterprise Solutions')], default='WEBSITE_DEVELOPMENT', max_length=100)),
                ('pricing_model', models.CharField(choices=[('FIXED', 'Fixed Price'), ('HOURLY', 'Hourly Rate')], default='FIXED', max_length=50)),
                ('estimated_delivery_days', models.IntegerField(default=7)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional_services',
            },
        ),
        migrations.CreateModel(
            name='ServiceLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website Form'), ('CAMPAIGN', 'Marketing Campaign'), ('MANUAL', 'Manual Entry'), ('REFERRAL', 'Referral Link')], default='WEBSITE', max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New Prospect'), ('CONTACTED', 'Contacted/Nurturing'), ('CONVERTED', 'Converted to Project'), ('LOST', 'Closed Lost')], default='NEW', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_leads', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='services.professionalservice')),
            ],
            options={
                'db_table': 'service_leads',
            },
        ),
        migrations.CreateModel(
            name='ServiceProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('IN_REVISION', 'In Revision'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=50)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_projects', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='services.professionalservice')),
            ],
            options={
                'db_table': 'service_projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='services.serviceproject')),
            ],
            options={
                'db_table': 'project_milestones',
            },
        ),
    ]
