# Generated by Django 5.0.14 on 2026-07-06 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Assignment heading.', max_length=255)),
                ('instructions', models.TextField(help_text='Detailed grading guidelines and prompt criteria.')),
                ('max_points', models.IntegerField(default=100, help_text='Max grading point capacity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Visually distinct badge title.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Details of how to earn badge.', null=True)),
                ('icon_url', models.CharField(blank=True, help_text='Creative badge icon vector SVG path URL.', max_length=512, null=True)),
                ('criteria', models.JSONField(default=dict, help_text='JSON structure configuration outlining triggers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'db_table': 'badges',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_url', models.CharField(blank=True, help_text='Cloud storage storage path of certificate PDF.', max_length=512, null=True)),
                ('signature_hash', models.CharField(help_text='Cryptographic SHA-256 validation identifier signature.', max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='CourseStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True)),
                ('node_type', models.CharField(choices=[('PROGRAM', 'Program'), ('SUBJECT', 'Subject'), ('COURSE', 'Course'), ('CHAPTER', 'Chapter'), ('TOPIC', 'Topic'), ('SUBTOPIC', 'Subtopic'), ('LESSON', 'Lesson')], help_text='The tier layer classifier of this curriculum unit.', max_length=20)),
                ('title', models.CharField(help_text='Header display title.', max_length=255)),
                ('slug', models.CharField(help_text='URL slug identifier.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of content unit.', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Sequential sorting index under the same parent.')),
                ('metadata', models.JSONField(default=dict, help_text='Flexible dynamic settings (e.g., video URL, duration, attachment details).')),
            ],
            options={
                'verbose_name': 'Course Structure',
                'verbose_name_plural': 'Course Structures',
                'db_table': 'course_structures',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Exam heading title.', max_length=255)),
                ('passing_score', models.DecimalField(decimal_places=2, default=70.0, help_text='Score percentage threshold required to pass.', max_digits=5)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Time allowance for complete attempt.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
                'db_table': 'exam_questions',
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Completion ratio of child lessons under this node.', max_digits=5)),
                ('is_completed', models.BooleanField(default=False, help_text='Has student successfully achieved 100% completion?')),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp of complete milestone.', null=True)),
            ],
            options={
                'verbose_name': 'Learning Progress',
                'verbose_name_plural': 'Learning Progresses',
                'db_table': 'learning_progress',
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Achieved percentage score.', max_digits=5, null=True)),
                ('session_data', models.JSONField(help_text='Tracks given student answers and correct keys.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Practice Session',
                'verbose_name_plural': 'Practice Sessions',
                'db_table': 'practice_sessions',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Project theme title.', max_length=255)),
                ('description', models.TextField(help_text='Comprehensive requirements description.')),
                ('requirements', models.JSONField(default=list, help_text='Serialized checklist array of deliverables.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='Prompt question text.')),
                ('question_type', models.CharField(default='MULTIPLE_CHOICE', help_text='Classification model of input layout.', max_length=50)),
                ('options', models.JSONField(default=list, help_text='List of choices.')),
                ('correct_answers', models.JSONField(default=list, help_text='Answer evaluation key indexes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question Bank',
                'verbose_name_plural': 'Question Banks',
                'db_table': 'question_banks',
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Status of educational enrollment.', max_length=50)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'db_table': 'student_enrollments',
            },
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_url', models.CharField(blank=True, help_text='Cloud storage storage URL of CV.', max_length=512, null=True)),
                ('experience_summary', models.TextField(help_text='Detailed overview of instruction background.')),
                ('subjects_requested', models.JSONField(default=list, help_text='Serialized list of topics the candidate seeks to instruct.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Recruitment processing status.', max_length=50)),
            ],
            options={
                'verbose_name': 'Teacher Application',
                'verbose_name_plural': 'Teacher Applications',
                'db_table': 'teacher_applications',
            },
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_info', models.JSONField(help_text='Serialized agenda configurations (calendar, times, recurrence).')),
                ('is_active', models.BooleanField(default=True, help_text='Is current scheduled class active?')),
            ],
            options={
                'verbose_name': 'Teacher Class',
                'verbose_name_plural': 'Teacher Classes',
                'db_table': 'teacher_classes',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'db_table': 'user_badges',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_payload', models.JSONField(help_text='Tracks text essay essay inputs and attachment storage URLs.')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='Awarded score by instructor.', max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Instructor feedback notations.', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, help_text='Timestamp when grade was finalized.', null=True)),
                ('assignment', models.ForeignKey(help_text='Linked assignment criteria.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.assignment')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'db_table': 'assignment_submissions',
            },
        ),
    ]
