# Generated by Django 5.0.14 on 2026-07-06 10:56

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, help_text='Grading instructor user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(help_text='Submitting student user.', on_delete=django.db.models.deletion.RESTRICT, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(help_text='Graduate student recipient.', on_delete=django.db.models.deletion.RESTRICT, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursestructure',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Self-referential link pointing to parent node in adjacency list.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='lms.coursestructure'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(help_text='Completed course module.', on_delete=django.db.models.deletion.RESTRICT, related_name='certificates', to='lms.coursestructure'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(help_text='Target Lesson node.', limit_choices_to={'node_type': 'LESSON'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lms.coursestructure'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(help_text='Parent Course node.', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='lms.coursestructure'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(help_text='Associated exam.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='lms.exam'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='node',
            field=models.ForeignKey(help_text='Associated syllabus block node.', on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lms.coursestructure'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='student',
            field=models.ForeignKey(help_text='Enrolled student user.', on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='course',
            field=models.ForeignKey(help_text='Linked Course curriculum node.', on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='lms.coursestructure'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='student',
            field=models.ForeignKey(help_text='Student participant.', on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ForeignKey(help_text='Parent Course node.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='lms.coursestructure'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='course',
            field=models.ForeignKey(help_text='Subject or Course node context of questions.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.coursestructure'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(help_text='Linked question bank node.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='lms.questionbank'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='course',
            field=models.ForeignKey(help_text='Target registered Course.', limit_choices_to={'node_type': 'COURSE'}, on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to='lms.coursestructure'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(help_text='Learner student user.', on_delete=django.db.models.deletion.RESTRICT, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Supervising administrator reviewer user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_teacher_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherapplication',
            name='user',
            field=models.ForeignKey(help_text='Applying candidate user.', on_delete=django.db.models.deletion.RESTRICT, related_name='teacher_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='course',
            field=models.ForeignKey(help_text='Assigned Course.', limit_choices_to={'node_type': 'COURSE'}, on_delete=django.db.models.deletion.RESTRICT, related_name='teacher_classes', to='lms.coursestructure'),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='teacher',
            field=models.ForeignKey(help_text='Instructing teacher user.', on_delete=django.db.models.deletion.RESTRICT, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(help_text='Unlocked badge.', on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='lms.badge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(help_text='Recipient user.', on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='coursestructure',
            index=models.Index(fields=['parent'], name='idx_course_struct_parent'),
        ),
        migrations.AddIndex(
            model_name='coursestructure',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='idx_course_struct_meta_gin'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['signature_hash'], name='idx_certificates_hash'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(condition=models.Q(('is_completed', False)), fields=['student', 'node'], name='idx_learning_progress_active'),
        ),
        migrations.AddConstraint(
            model_name='learningprogress',
            constraint=models.UniqueConstraint(fields=('student', 'node'), name='uq_learning_progress_student_node'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('exam', 'question'), name='uq_exam_questions_exam_question'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='uq_student_enrollments_student_course'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='uq_user_badges_user_badge'),
        ),
    ]
