# Generated by Django 5.1.4 on 2026-07-08 08:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='created_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='updated_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='created_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
        migrations.AddField(
            model_name='badge',
            name='updated_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='updated_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='created_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='updated_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='created_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='updated_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='created_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='updated_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbadge',
            name='created_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='updated_by',
            field=models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True),
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True)),
                ('submission_payload', models.JSONField(help_text='Tracks text essay essay inputs and attachment storage URLs.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
                'db_table': 'project_submissions',
            },
        ),
    ]
