# Generated by Django 5.1.4 on 2026-07-08 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_assignmentsubmission_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Header title of the live class.', max_length=255)),
                ('scheduled_at', models.DateTimeField(help_text='Date and time of stream launch.')),
                ('duration_minutes', models.IntegerField(help_text='Stream target duration in minutes.')),
                ('stream_url', models.CharField(blank=True, help_text='Live stream RTMP/WebRTC entry link.', max_length=512, null=True)),
                ('course', models.ForeignKey(help_text='Assigned Course.', limit_choices_to={'node_type': 'COURSE'}, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='lms.coursestructure')),
                ('teacher', models.ForeignKey(help_text='Instructing teacher user.', on_delete=django.db.models.deletion.RESTRICT, related_name='live_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Classes',
                'db_table': 'live_classes',
            },
        ),
    ]
