# Generated by Django 5.1.4 on 2026-07-09 04:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_liveclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp of when the record was soft-deleted.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict, help_text='Dictionary of question responses: {question_id: selected_options_list}')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated percentage score.', max_digits=5, null=True)),
                ('passed', models.BooleanField(default=False, help_text='Whether score meets passing threshold.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp of submission.', null=True)),
                ('status', models.CharField(default='STARTED', help_text='State of attempt: STARTED, SUBMITTED, TIMED_OUT', max_length=50)),
                ('exam', models.ForeignKey(help_text='Linked exam.', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.exam')),
                ('student', models.ForeignKey(help_text='Student participant.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'db_table': 'exam_attempts',
            },
        ),
    ]
