# Generated by Django 5.1.4 on 2026-07-18 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_examattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='meeting_id',
            field=models.CharField(blank=True, help_text='External WebRTC channel/room ID.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed')], default='SCHEDULED', help_text='Active lifecycle stage of live class event.', max_length=20),
        ),
        migrations.CreateModel(
            name='BreakoutRoom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('meeting_id', models.CharField(blank=True, max_length=255, null=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_rooms', to='lms.liveclass')),
            ],
            options={
                'db_table': 'live_breakout_rooms',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_syncs', to='lms.liveclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_calendar_events',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='lms.liveclass')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_chat_messages',
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='lms.liveclass')),
            ],
            options={
                'db_table': 'live_sessions',
            },
        ),
        migrations.CreateModel(
            name='MeetingAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_participants', models.IntegerField(default=0)),
                ('average_engagement_score', models.FloatField(default=0.0)),
                ('peak_concurrent_users', models.IntegerField(default=0)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to='lms.liveclass')),
            ],
            options={
                'db_table': 'live_meeting_analytics',
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRESENTER', 'Presenter'), ('ATTENDEE', 'Attendee')], default='ATTENDEE', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lms.liveclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_meeting_participants',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='lms.liveclass')),
            ],
            options={
                'db_table': 'live_polls',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lms.poll')),
            ],
            options={
                'db_table': 'live_poll_options',
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='lms.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='lms.poll')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_poll_votes',
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.URLField(max_length=512)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='lms.liveclass')),
            ],
            options={
                'db_table': 'live_recordings',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remind_at', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='lms.liveclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_reminders',
            },
        ),
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canvas_data', models.TextField(help_text='Serialized JSON drawing commands')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboards', to='lms.liveclass')),
            ],
            options={
                'db_table': 'live_whiteboards',
            },
        ),
    ]
