# Generated by Django 5.1.4 on 2026-07-08 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the organization/workspace.', max_length=255)),
                ('subdomain', models.CharField(blank=True, help_text='Custom access subdomain.', max_length=100, null=True, unique=True)),
                ('org_type', models.CharField(choices=[('PERSONAL', 'Personal Workspace'), ('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('COMPANY', 'Company'), ('NGO', 'NGO'), ('COACHING', 'Coaching Institute')], default='PERSONAL', help_text='Classification type of organization.', max_length=50)),
                ('logo_url', models.CharField(blank=True, help_text='Custom brand logo URL.', max_length=512, null=True)),
                ('primary_color', models.CharField(default='#4F46E5', help_text='Brand primary HEX color code.', max_length=7)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Custom settings profile (allowed domains, security rules).')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, help_text='Failed authentication counts.'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp blocking login access.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.JSONField(blank=True, default=list, help_text='List of user achievements.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_image_url',
            field=models.CharField(blank=True, help_text='CDN profile cover picture URL.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic list of education history.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic list of professional experience.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of languages spoken.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict, help_text='User privacy settings profile.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.JSONField(blank=True, default=list, help_text='Dynamic list of projects.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of user skills.'),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_attempted', models.EmailField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'db_table': 'login_history',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('OWNER', 'Workspace Owner'), ('ADMIN', 'Workspace Admin'), ('MEMBER', 'Workspace Member'), ('GUEST', 'Workspace Guest')], default='MEMBER', max_length=50)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(help_text='Linked organization.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.organization')),
                ('user', models.ForeignKey(help_text='Linked user.', on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
                'db_table': 'organization_members',
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='uq_org_member')],
            },
        ),
    ]
