# Generated by Django 5.1.4 on 2026-07-09 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('codename', models.CharField(help_text='Capability codename (e.g. TEACHING).', max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('INSTANT', 'Instant Activation'), ('APPROVAL_REQUIRED', 'Requires Approval')], default='INSTANT', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('default_settings', models.JSONField(blank=True, default=dict)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'db_table': 'capabilities',
            },
        ),
        migrations.CreateModel(
            name='CapabilityApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Re-submitted After Rejection')], default='PENDING', max_length=50)),
                ('application_data', models.JSONField(blank=True, default=dict)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.capability')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capability Application',
                'verbose_name_plural': 'Capability Applications',
                'db_table': 'capability_applications',
            },
        ),
        migrations.CreateModel(
            name='CapabilityPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_permissions', to='users.capability')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_permissions', to='users.permission')),
            ],
            options={
                'verbose_name': 'Capability Permission',
                'verbose_name_plural': 'Capability Permissions',
                'db_table': 'capability_permissions',
                'constraints': [models.UniqueConstraint(fields=('capability', 'permission'), name='uq_capability_permission')],
            },
        ),
        migrations.CreateModel(
            name='UserCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Approval'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Voluntarily Deactivated'), ('REJECTED', 'Application Rejected')], default='PENDING', max_length=50)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_capabilities', to=settings.AUTH_USER_MODEL)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_capabilities', to='users.capability')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Capability',
                'verbose_name_plural': 'User Capabilities',
                'db_table': 'user_capabilities',
                'constraints': [models.UniqueConstraint(fields=('user', 'capability'), name='uq_user_capability')],
            },
        ),
    ]
