# Generated by Django 5.0.14 on 2026-07-06 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoiced currency sum.', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency ISO code.', max_length=3)),
                ('payment_gateway', models.CharField(default='STRIPE', help_text='Gateway billing provider name.', max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Unique external transaction reference ID from provider gateway.', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Current transaction invoicing state.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, help_text='Associated course registry subscription link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='lms.studentenrollment')),
                ('user', models.ForeignKey(help_text='Payer student account user.', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=4, default=0.0, help_text='Compute/cache sum of transaction ledgers.', max_digits=15)),
                ('currency', models.CharField(default='VIDYA', help_text='Platform token ledger currency representation.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User owner of the wallet.', on_delete=django.db.models.deletion.RESTRICT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], help_text='Point direction classification flow.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Ledger value quantity.', max_digits=15)),
                ('description', models.CharField(blank=True, help_text='Short narrative summarizing event details.', max_length=255, null=True)),
                ('reference_id', models.UUIDField(blank=True, help_text='Reference linking back to enrollment, project, or event.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(help_text='Associated point ledger wallet.', on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['wallet'], name='idx_transactions_wallet')],
            },
        ),
    ]
