# Generated by Django 5.1.4 on 2026-07-19 04:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Discount code tag.', max_length=50, unique=True)),
                ('type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed')], help_text='Discount discount calculation method.', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value.', max_digits=10)),
                ('usage_limit', models.IntegerField(default=100, help_text='Maximum allowed usage count.')),
                ('usage_count', models.IntegerField(default=0, help_text='Current usage count.')),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum cart value required.', max_digits=10)),
                ('expiry_date', models.DateField(help_text='Expiration limit.')),
                ('is_active', models.BooleanField(default=True, help_text='Is the discount active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='RevenueSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Summary period date.', unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue.', max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Total tax.', max_digits=15)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0.0, help_text='Total platform fee.', max_digits=15)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0.0, help_text='Total paid teacher cashouts.', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Revenue Summary Record',
                'verbose_name_plural': 'Revenue Summary Records',
                'db_table': 'revenue_summaries',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Plan tier name.', max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly subscription rate.', max_digits=10)),
                ('duration_days', models.IntegerField(default=30, help_text='Billing duration in days.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='GSTRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Linked invoice serial number.', max_length=50, unique=True)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Pre-tax amount.', max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, help_text='CGST tax portion.', max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, help_text='SGST tax portion.', max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, help_text='IGST tax portion.', max_digits=10)),
                ('total_gst', models.DecimalField(decimal_places=2, help_text='Summed GST tax.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(help_text='Origin checkout payment.', on_delete=django.db.models.deletion.RESTRICT, related_name='gst_record', to='wallets.payment')),
            ],
            options={
                'verbose_name': 'GST Record',
                'verbose_name_plural': 'GST Records',
                'db_table': 'gst_records',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Invoice reference serial number.', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Net taxable amount.', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='GST tax collected.', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Gross invoice total.', max_digits=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('CANCELLED', 'Cancelled')], default='PAID', help_text='Invoicing billing status.', max_length=50)),
                ('gst_number', models.CharField(default='27AAAAA1111A1Z1', help_text='Client GSTIN registration.', max_length=15)),
                ('items', models.JSONField(default=list, help_text='Serialized dynamic invoice item list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(help_text='Linked gateway payment.', on_delete=django.db.models.deletion.RESTRICT, related_name='invoice', to='wallets.payment')),
                ('user', models.ForeignKey(help_text='Billed user account.', on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='PaymentAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='Logged action name.', max_length=100)),
                ('actor_email', models.CharField(help_text='User executing the action.', max_length=255)),
                ('details', models.JSONField(default=dict, help_text='Context metadata.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, help_text='Linked payment ledger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='wallets.payment')),
            ],
            options={
                'verbose_name': 'Payment Audit Log',
                'verbose_name_plural': 'Payment Audit Logs',
                'db_table': 'payment_audits',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Converted'), ('REWARDED', 'Rewarded')], default='PENDING', help_text='Referral onboarding status.', max_length=50)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Affiliate reward earnings.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(help_text='Referred scholar account.', on_delete=django.db.models.deletion.RESTRICT, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='Referring advocate user.', on_delete=django.db.models.deletion.RESTRICT, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Linkage',
                'verbose_name_plural': 'Referral Linkages',
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refunded monetary sum.', max_digits=10)),
                ('reason', models.CharField(default='Administrative Refund', help_text='Reason for refund.', max_length=255)),
                ('gateway_refund_id', models.CharField(blank=True, help_text='Gateway refund reference ID.', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='SUCCEEDED', help_text='Refund status.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(help_text='Origin payment transaction.', on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='wallets.payment')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'refunds',
            },
        ),
        migrations.CreateModel(
            name='TeacherPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payout amount.', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', help_text='Payout status.', max_length=50)),
                ('payout_method', models.CharField(default='BANK_TRANSFER', help_text='Payout disbursement channel.', max_length=50)),
                ('reference_id', models.CharField(blank=True, help_text='Bank payout transaction number.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(help_text='Recipient instructor account.', on_delete=django.db.models.deletion.RESTRICT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Payout Record',
                'verbose_name_plural': 'Teacher Payout Records',
                'db_table': 'teacher_payouts',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='ACTIVE', help_text='Subscription status.', max_length=50)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Selected subscription plan.', on_delete=django.db.models.deletion.RESTRICT, related_name='user_subscriptions', to='wallets.subscriptionplan')),
                ('user', models.ForeignKey(help_text='Subscribing user.', on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'user_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(help_text='Redeemed coupon.', on_delete=django.db.models.deletion.RESTRICT, related_name='usages', to='wallets.coupon')),
                ('payment', models.ForeignKey(help_text='Linked checkout transaction.', on_delete=django.db.models.deletion.RESTRICT, related_name='coupon_usages', to='wallets.payment')),
                ('user', models.ForeignKey(help_text='Customer user.', on_delete=django.db.models.deletion.RESTRICT, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon Usage Record',
                'verbose_name_plural': 'Coupon Usage Records',
                'db_table': 'coupon_usages',
                'unique_together': {('coupon', 'user', 'payment')},
            },
        ),
    ]
