# Generated by Django 5.0.14 on 2026-07-06 10:56

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Blog post author user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Comment author user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Parent blog.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.blog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Nested comment reference.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cms.comment'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Post author user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Thread creator user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='forum',
            field=models.ForeignKey(help_text='Parent forum category.', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='cms.forum'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(help_text='Parent thread.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cms.forumtopic'),
        ),
        migrations.AddField(
            model_name='like',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Linked blog.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cms.blog'),
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='Linked comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cms.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Linked forum post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cms.forumpost'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(help_text='User who liked.', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent menu node for nested navigation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.navigationmenu'),
        ),
        migrations.AddField(
            model_name='navigationmenu',
            name='permission',
            field=models.ForeignKey(blank=True, help_text='Visibility gate permission constraint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_menus', to='users.permission'),
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.ForeignKey(blank=True, help_text='User who authored the page layout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, help_text='User submitting complaint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='target_comment',
            field=models.ForeignKey(blank=True, help_text='Violating comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reports', to='cms.comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='target_post',
            field=models.ForeignKey(blank=True, help_text='Violating forum post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reports', to='cms.forumpost'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Author user of tutorial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='blog',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='uq_blogs_slug'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('user', 'post'), name='uq_likes_user_post'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('blog__isnull', False)), fields=('user', 'blog'), name='uq_likes_user_blog'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment'), name='uq_likes_user_comment'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=django.contrib.postgres.indexes.GinIndex(fields=['layout_data'], name='idx_pages_layout_data_gin'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('is_published', True)), fields=['slug'], name='idx_pages_active_slug'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='uq_pages_slug'),
        ),
        migrations.AddConstraint(
            model_name='tutorial',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='uq_tutorials_slug'),
        ),
    ]
