# Generated by Django 5.0.14 on 2026-07-06 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Is tutorial visible to public?'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of publication.', null=True),
        ),
        migrations.AddIndex(
            model_name='tutorial',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True), ('is_published', True)), fields=['slug'], name='idx_tutorials_active_slug'),
        ),
    ]
