# Generated by Django 5.1.4 on 2026-07-12 04:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('query_string', models.CharField(help_text='Normalized query text.', max_length=255, unique=True)),
                ('total_queries', models.PositiveIntegerField(default=0, help_text='Total number of searches executed for this query.')),
                ('total_results', models.PositiveIntegerField(default=0, help_text='Average or last returned result count.')),
                ('click_through_rate', models.FloatField(default=0.0, help_text='Percentage of queries resulting in a click (0.0 to 1.0).')),
                ('avg_dwell_time', models.FloatField(default=0.0, help_text='Average time in seconds spent on clicked results.')),
            ],
            options={
                'verbose_name': 'Search Analytics Entry',
                'verbose_name_plural': 'Search Analytics Entries',
                'db_table': 'search_analytics',
                'ordering': ['-total_queries'],
            },
        ),
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('query_key', models.CharField(help_text='The unique MD5 or string key identifier for query parameters.', max_length=255, unique=True)),
                ('results_json', models.JSONField(help_text='Cached list of matching document objects.')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Expiry timestamp for cached results.')),
            ],
            options={
                'verbose_name': 'Search Cache Entry',
                'verbose_name_plural': 'Search Cache Entries',
                'db_table': 'search_caches',
                'ordering': ['expires_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('entity_type', models.CharField(db_index=True, help_text="The model class name of the source entity (e.g., 'Article', 'Course').", max_length=100)),
                ('entity_id', models.UUIDField(db_index=True, help_text='UUID primary key of the source database record.')),
                ('title', models.CharField(help_text='The main searchable title of the entity.', max_length=255)),
                ('excerpt', models.TextField(blank=True, help_text='A short teaser or description text.', null=True)),
                ('body', models.TextField(blank=True, help_text='Full text content for deep searching.', null=True)),
                ('tags', models.CharField(blank=True, help_text='Space-separated list of tag/keyword names.', max_length=1000, null=True)),
                ('categories', models.CharField(blank=True, help_text='Comma-separated category names.', max_length=500, null=True)),
                ('author_name', models.CharField(blank=True, help_text='Searchable author name.', max_length=150, null=True)),
                ('url_path', models.CharField(help_text='Canonical public relative path or URL to view the detail page.', max_length=512)),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Is the content publicly active.')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When this content was published.', null=True)),
                ('search_vector', models.TextField(blank=True, help_text='Pre-computed search tokens/lexemes.', null=True)),
                ('meta_data', models.JSONField(blank=True, default=dict, help_text='Additional key-value fields for dynamic facets, filtering, and scoring.')),
            ],
            options={
                'verbose_name': 'Search Document',
                'verbose_name_plural': 'Search Documents',
                'db_table': 'search_documents',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchFacet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('name', models.CharField(help_text="Human readable facet label (e.g. 'Level', 'Format').", max_length=100, unique=True)),
                ('field_name', models.CharField(help_text='The JSON key inside SearchDocument.meta_data or model attribute name.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this facet is active on search queries.')),
            ],
            options={
                'verbose_name': 'Search Facet',
                'verbose_name_plural': 'Search Facets',
                'db_table': 'search_facets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('name', models.CharField(help_text='Search index name (e.g. articles, courses, books)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the index scope.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this index is active and searched.')),
                ('last_indexed_at', models.DateTimeField(blank=True, help_text='Timestamp of the last full re-indexing execution.', null=True)),
            ],
            options={
                'verbose_name': 'Search Index',
                'verbose_name_plural': 'Search Indexes',
                'db_table': 'search_indexes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('phrase', models.CharField(help_text='Normalized phrase suggestion.', max_length=255, unique=True)),
                ('weight', models.FloatField(default=1.0, help_text='Display priority weight for auto-completion suggestions.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this suggestion is active and visible.')),
            ],
            options={
                'verbose_name': 'Search Suggestion',
                'verbose_name_plural': 'Search Suggestions',
                'db_table': 'search_suggestions',
                'ordering': ['-weight', 'phrase'],
            },
        ),
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('term', models.CharField(help_text='The primary search keyword.', max_length=255, unique=True)),
                ('synonyms', models.TextField(help_text='Comma-separated synonyms that map to this primary term.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the synonym mapping is active.')),
            ],
            options={
                'verbose_name': 'Search Synonym',
                'verbose_name_plural': 'Search Synonyms',
                'db_table': 'search_synonyms',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('term', models.CharField(help_text='The normalized search query string.', max_length=255, unique=True)),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Count of times this exact query has been searched.')),
                ('last_queried_at', models.DateTimeField(auto_now=True, help_text='The most recent timestamp this query was run.')),
            ],
            options={
                'verbose_name': 'Search Term',
                'verbose_name_plural': 'Search Terms',
                'db_table': 'search_terms',
                'ordering': ['-frequency', '-last_queried_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('query', models.CharField(help_text='The search query text entered by the user.', max_length=255)),
                ('filters_applied', models.JSONField(blank=True, default=dict, help_text='JSON representation of filter key-values applied.')),
                ('results_count', models.PositiveIntegerField(default=0, help_text='Number of matching documents found.')),
                ('searched_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the search request was executed.')),
                ('user', models.ForeignKey(blank=True, help_text='Optional link to the authenticated user who performed the search.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History Record',
                'verbose_name_plural': 'Search History Records',
                'db_table': 'search_histories',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user clicked the result.')),
                ('position', models.PositiveIntegerField(help_text='The rank position index of the clicked document (e.g. 1 for top result).')),
                ('document', models.ForeignKey(help_text='The document that was clicked.', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='search.searchdocument')),
                ('history', models.ForeignKey(blank=True, help_text='The historical search session during which this click occurred.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='search.searchhistory')),
            ],
            options={
                'verbose_name': 'Search Click Record',
                'verbose_name_plural': 'Search Click Records',
                'db_table': 'search_clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='index',
            field=models.ForeignKey(help_text='The index this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='search.searchindex'),
        ),
        migrations.CreateModel(
            name='SearchRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('query', models.CharField(help_text='The query string that triggers this ranking rule.', max_length=255)),
                ('boost_score', models.FloatField(default=1.0, help_text='Relevance multiplier or score addition for matching search document.')),
                ('is_pinned', models.BooleanField(default=False, help_text='Force document to be pinned as the top search result.')),
                ('document', models.ForeignKey(help_text='Target document to boost.', on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='search.searchdocument')),
            ],
            options={
                'verbose_name': 'Search Ranking Override',
                'verbose_name_plural': 'Search Ranking Overrides',
                'db_table': 'search_rankings',
            },
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=models.Index(fields=['entity_type', 'entity_id'], name='idx_search_doc_entity'),
        ),
        migrations.AddIndex(
            model_name='searchdocument',
            index=models.Index(fields=['is_published', 'published_at'], name='idx_search_doc_pub_status'),
        ),
        migrations.AddConstraint(
            model_name='searchdocument',
            constraint=models.UniqueConstraint(fields=('index', 'entity_type', 'entity_id'), name='uq_search_document_index_entity'),
        ),
        migrations.AddIndex(
            model_name='searchranking',
            index=models.Index(fields=['query'], name='idx_search_rank_query'),
        ),
        migrations.AddConstraint(
            model_name='searchranking',
            constraint=models.UniqueConstraint(fields=('document', 'query'), name='uq_search_ranking_doc_query'),
        ),
    ]
