# Generated by Django 5.1.4 on 2026-07-09 04:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who updated this record.', null=True)),
                ('page_type', models.CharField(help_text='Classification namespace (e.g., COURSE, BLOG, BOOK, PRODUCT, PORTFOLIO, RESUME, WEBSITE, ORGANIZATION, PROFILE)', max_length=50)),
                ('page_id', models.CharField(db_index=True, help_text='Linked target page primary identifier.', max_length=255)),
                ('title', models.CharField(help_text='Visual visual title label.', max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.CharField(blank=True, max_length=512, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.CharField(blank=True, max_length=512, null=True)),
                ('twitter_title', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_description', models.TextField(blank=True, null=True)),
                ('twitter_image', models.CharField(blank=True, max_length=512, null=True)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
                'db_table': 'seo_pages',
                'constraints': [models.UniqueConstraint(fields=('page_type', 'page_id'), name='uq_seo_page_type_id')],
            },
        ),
        migrations.CreateModel(
            name='SEOAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seo_score', models.IntegerField(default=0)),
                ('readability_score', models.IntegerField(default=0)),
                ('broken_links', models.JSONField(blank=True, default=list)),
                ('duplicate_title', models.BooleanField(default=False)),
                ('duplicate_description', models.BooleanField(default=False)),
                ('missing_alt_images', models.IntegerField(default=0)),
                ('missing_h1', models.BooleanField(default=False)),
                ('missing_schema', models.BooleanField(default=False)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='seo.seopage')),
            ],
            options={
                'verbose_name': 'SEO Audit',
                'verbose_name_plural': 'SEO Audits',
                'db_table': 'seo_audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
